### ISSUE TITLE
Issue with Monte Carlo Error : the rate ((nan,nan)) is not finite in move Shift one operator

### ISSUE THREAD

**Issue by hrishitbanerjee** [TRIQS/cthyb#113]
Hii,
I am getting this particular error while doing calculations with certain systems like LaTiO3 and LaMnO3. The calculations are stopping after a few warmup steps only.
Can anyone comment on why this is happening and how it can be solved?
Thanks and best regards
Hrishit.

Traceback (most recent call last):
  File "LTO-ortho.py", line 144, in <module>
    S.solve(h_int = H, **p)
  File "/temp/AG-CMS/TRIQS/2.1/complex/lib/python2.7/site-packages/triqs_cthyb/solver.py", line 130, in solve
    solve_status = SolverCore.solve(self, **params_kw)
RuntimeError: .. Error occurred at Tue May 21 15:23:19 2019

.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /temp/AG-CMS/TRIQS/2.1/complex/include/triqs/mc_tools/./mc_move_set.hpp : 205

Monte Carlo Error : the rate ((nan,nan)) is not finite in move Shift one operator
.. Error occurred on node 0

**Comment by HugoStrand** [comment]
Thank you Nils!

Dear Hrishit,

I am not sure what is going wrong. But I suspect that this can have to do with bad data in the single-particle propagator that you pass to cthyb (G0_iw). Could you plot and look at the G0_iw that gives this result?

Best regards,
Hugo

**Comment by hrishitbanerjee** [comment]
Hi 
I indeed plotted the G0_iw. It looks ok to me. Here is the plot.
![LTO-ortho-G_iw](https://user-images.githubusercontent.com/40570674/58420609-050d9b80-808e-11e9-8fe6-64fbe3c41c36.png)

**Comment by HugoStrand** [comment]
Dear Hrishit,

Thank you for having a look. G0_iw does not look crazy, but you seem to have substantial off-diagonal components, which should give you a sign problem. It will not be easy to help you further without some more information from your side.

Could you please provide an, as simple as possible, example script (with input G0_iw) that reproduces your problem? E.g. take the G0_iw that causes the error, store it to a h5-file, and write a script that reads it, runs cthyb, and crashes.

With that I could try to reproduce your problem and debug it.

Best regards,
Hugo

**Comment by hrishitbanerjee** [comment]
Dear Hugo,
Thanks a lot for looking into this.
I am attaching the script and the h5 file that I used for this here in a zip format
Thanks and best regards
Hrishit

[LTo-ortho.zip](https://github.com/TRIQS/cthyb/files/3251522/LTo-ortho.zip)

**Comment by HugoStrand** [comment]
Dear Hrishit,

I have looked at your problem and the TRIQS/cthyb solver prints big warnings already before starting the simulation, saying that the tail fit has a big error.

To make a long story short the bath Green's function you are giving to the solver is not a physical Green's function (it does not have the 1/i\omega_n asymptotic behavior). For details see below.

So you will have to take a good look at dft_tools and the Green's functions you are getting out of it and make sure they obey the physical constraints on Matsubara Green's functions.

Best, Hugo



Since the self energy is zero `G0_iw` is equal to the local Green's function of the lattice stored in `dmft_results/G_0` in your h5 file. If we plot `G_0` in imaginary time it looks rather wild, 
![figure_G_tau](https://user-images.githubusercontent.com/1188035/59112883-f175f680-8911-11e9-928f-35a5edfc2d28.png)

however it is more informative to plot the quantity `B = inverse(G_0) - iOmega_n`
![figure_inv_G_iw_minus_iOmega_n](https://user-images.githubusercontent.com/1188035/59112897-f9ce3180-8911-11e9-9a51-eb8143208d28.png)

Here we see that there are linear imaginary terms remaining in `B` which should not be the case if `G_0` had the physical form

``` G_0 = 1/( iOmega_n - E - \Delta(iOmega_n) ) ```

since then

``` B = 1/G_0 - iOmega_n = E - \Delta(iOmega_n) ```

The same property in imaginary time is equivalent to the discontinuity that any physical Green's function has to satisfy (due to the fermionic commutation relations):

``` G(0) + G(\beta) = - I ```, where `I` is the identity matrix.

If we compute this using `G_0` from your data we get

```
Re[d] =
[[-7.01551837e-01 -9.30666952e-11 -1.92431409e-02]
 [-9.30535164e-11 -9.62620424e-01  1.21455897e-09]
 [-1.92431409e-02  1.21455557e-09 -9.30579572e-01]]
Im[d] =
[[ 5.48961868e-13 -8.64718528e-03 -2.76674000e-09]
 [ 8.64718528e-03  7.51034373e-13  2.74267221e-03]
 [ 2.76677099e-09 -2.74267221e-03  7.29034096e-13]]
```
which is pretty far from one minus the unity matrix `- I`.

For the script doing the plotting and calculations please see below.

```python
import numpy as np
from pytriqs.gf import *
from pytriqs.archive import HDFArchive

with HDFArchive('LTO-ortho.h5','r') as ar:
    G_0 = ar['dmft_output']['G_0']['up_0']

# -- For a physical Green's function G = 1/(i\omega_n - E - \Delta(i\omega_n))
# -- the expression [G]^{-1} - i\omega_n should not have any imaginary linear term.
    
A = G_0.copy()
A << inverse(A)
B = A.copy()
B << B - iOmega_n

beta = G_0.mesh.beta
G_tau = Gf(mesh=MeshImTime(beta, 'Fermion', 10000), target_shape=[3,3])
G_tau << InverseFourier(G_0)

# -- A physical Green's function has to satisfy
# G(0) + G(\beta) = -I, where I is the identity matrix

d = G_tau(0) + G_tau(beta)

print 'Re[d] =\n', d.real
print 'Im[d] =\n', d.imag

from pytriqs.plot.mpl_interface import oplot, oploti, oplotr, plt

plt.figure(figsize=(8,6))
subp = [3, 3, 1]
for i1, i2 in np.ndindex(3, 3):
    plt.subplot(*subp); subp[-1] += 1
    oplot(G_tau[i1, i2])

plt.tight_layout()
plt.savefig('figure_G_tau.png', dpi=600)

plt.figure(figsize=(8,6))
subp = [3, 3, 1]
for i1, i2 in np.ndindex(3, 3):
    plt.subplot(*subp); subp[-1] += 1
    oplot(B[i1, i2])
    
plt.tight_layout()
plt.savefig('figure_inv_G_iw_minus_iOmega_n.png', dpi=600)
    
plt.show()
```

**Comment by hrishitbanerjee** [comment]
Dear Hugo
Thanks a lot for the detailed analysis. So it seems that the main problem is with the input from the DFT itself. I am taking a detailed look at this. 
Regards,
Hrishit.

**Comment by HugoStrand** [comment]
I am closing this issue due to inactivity. Please reopen if needed.
